[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
remappings = [
    "drosera-contracts/=lib/contracts/src/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
holesky = "https://holesky.infura.io/v3/${INFURA_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
