[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
hoodi = "https://ethereum-hoodi-rpc.publicnode.com"
